Shfmt on stuff

diff --git a/dependencies/change-shell b/dependencies/change-shell
--- a/dependencies/change-shell
+++ b/dependencies/change-shell
@@ -1,99 +1,99 @@
 #! /usr/bin/env bash
 
-containsElement () {
-  local e match="$1"
-  shift
-  for e; do [[ "$e" == "$match" ]] && return 0; done
-  return 1
+containsElement() {
+	local e match="$1"
+	shift
+	for e; do [[ "$e" == "$match" ]] && return 0; done
+	return 1
 }
 
 select_shell() {
-    PS3='Please enter your new shell: '
-    local shells=("bash" "fish" "zsh")
-    select opt in "${shells[@]}"; do
-        if containsElement "${opt}" "${shells[@]}"; then
-            printf "%s" "$opt"
-            break
-        else
-            continue
-        fi
-    done
+	PS3='Please enter your new shell: '
+	local shells=("bash" "fish" "zsh")
+	select opt in "${shells[@]}"; do
+		if containsElement "${opt}" "${shells[@]}"; then
+			printf "%s" "$opt"
+			break
+		else
+			continue
+		fi
+	done
 }
 
 find_mgr() {
-    local package_managers=("brew" "pacman" "apt" "dnf")
-    for pkg_mgr in "${package_managers[@]}"; do
-        if type -p "${pkg_mgr}" >/dev/null 2>&1; then
-            printf "%s" "${pkg_mgr}"
-            return 0
-        fi
-    done
+	local package_managers=("brew" "pacman" "apt" "dnf")
+	for pkg_mgr in "${package_managers[@]}"; do
+		if type -p "${pkg_mgr}" >/dev/null 2>&1; then
+			printf "%s" "${pkg_mgr}"
+			return 0
+		fi
+	done
 
-    printf "%s\n" "ERROR: no supported package manager was not installed" >&2
-    exit 1
+	printf "%s\n" "ERROR: no supported package manager was not installed" >&2
+	exit 1
 }
 
 find_path() {
-    local mgr
-    mgr="$(find_mgr)"
+	local mgr
+	mgr="$(find_mgr)"
 
-    case "${mgr}" in
-    "brew")
-        : "$(brew --prefix)/bin"
-        ;;
-    *)
-        : "/usr/bin"
-        ;;
-    esac
+	case "${mgr}" in
+	"brew")
+		: "$(brew --prefix)/bin"
+		;;
+	*)
+		: "/usr/bin"
+		;;
+	esac
 
-    printf "%s" "$_"
+	printf "%s" "$_"
 }
 
 install_with_mgr() {
-    local mgr
-    mgr="$(find_mgr)"
+	local mgr
+	mgr="$(find_mgr)"
 
-    case "${mgr}" in
-    "brew")
-        : "brew install"
-        ;;
-    "pacman")
-        : "sudo pacman -S"
-        ;;
-    "apt")
-        : "sudo apt install"
-        ;;
-    "yum")
-        : "sudo yum install"
-        ;;
-    *)
-        printf "%s\n" "ERROR: ${mgr} is not supported" >&2
-        exit 1
-        ;;
-    esac
+	case "${mgr}" in
+	"brew")
+		: "brew install"
+		;;
+	"pacman")
+		: "sudo pacman -S"
+		;;
+	"apt")
+		: "sudo apt install"
+		;;
+	"yum")
+		: "sudo yum install"
+		;;
+	*)
+		printf "%s\n" "ERROR: ${mgr} is not supported" >&2
+		exit 1
+		;;
+	esac
 
-    # Install shell with correct install command
-    "$_" "$1" >/dev/null 2>&1
+	# Install shell with correct install command
+	"$_" "$1" >/dev/null 2>&1
 }
 
 install_shell() {
-    local shell_path
-    shell_path="$(find_path)/$1"
+	local shell_path
+	shell_path="$(find_path)/$1"
 
-    if [ ! -f "${shell_path}" ]; then
-        install_with_mgr "$1"
-    fi
-    printf "%s" "$shell_path"
+	if [ ! -f "${shell_path}" ]; then
+		install_with_mgr "$1"
+	fi
+	printf "%s" "$shell_path"
 }
 
 change_shell() {
-    local your_shell
-    your_shell="$(install_shell "$1")"
+	local your_shell
+	your_shell="$(install_shell "$1")"
 
-    printf "%s\n" "Your shell will be set to ${your_shell}"
-    grep "$your_shell" /etc/shells >/dev/null || printf "%s" "$your_shell" | sudo tee -a /etc/shells
-    printf "\n"
-    chsh -s "$your_shell" "$USER"
+	printf "%s\n" "Your shell will be set to ${your_shell}"
+	grep "$your_shell" /etc/shells >/dev/null || printf "%s" "$your_shell" | sudo tee -a /etc/shells
+	printf "\n"
+	chsh -s "$your_shell" "$USER"
 }
 
 change_shell "$(select_shell)"
diff --git a/dependencies/dependencies-Arch b/dependencies/dependencies-Arch
--- a/dependencies/dependencies-Arch
+++ b/dependencies/dependencies-Arch
@@ -1,50 +1,48 @@
 #!/usr/bin/env bash
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 
 info() {
-  printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
+	printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
 }
 
 user() {
-  printf "\r  [ \033[0;33m??\033[0m ] %s\n" "$1"
+	printf "\r  [ \033[0;33m??\033[0m ] %s\n" "$1"
 }
 
 success() {
-  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
+	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
 }
 
 fail() {
-  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
-  echo ''
-  exit
+	printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
+	echo ''
+	exit
 }
 
 # Verifiy if we're on bash 4 or greater
-bash_compatible()
-{
-  if [ "${BASH_VERSINFO[0]}" -lt 4 ]; then
-    return 0
-  else
-    return 1
-  fi
+bash_compatible() {
+	if [ "${BASH_VERSINFO[0]}" -lt 4 ]; then
+		return 0
+	else
+		return 1
+	fi
 }
 
 # Fetches all dependencies from Pacfile and expands them, separating by space
-get_dependencies()
-{
-  if [ -f "${DIR}/Pacfile" ]; then
-    local file_data
-    if bash_compatible; then
-        IFS=$' ' read -d "" -ra file_data < "${DIR}/Pacfile"
-    else
-      mapfile -t file_data < "${DIR}/Pacfile"
-    fi
-    printf "%s " "${file_data[@]}"
-  else
-    printf "%s" "Could not find Pacfile in ${DIR}..."
-    exit 1
-  fi
+get_dependencies() {
+	if [ -f "${DIR}/Pacfile" ]; then
+		local file_data
+		if bash_compatible; then
+			IFS=$' ' read -d "" -ra file_data <"${DIR}/Pacfile"
+		else
+			mapfile -t file_data <"${DIR}/Pacfile"
+		fi
+		printf "%s " "${file_data[@]}"
+	else
+		printf "%s" "Could not find Pacfile in ${DIR}..."
+		exit 1
+	fi
 }
 
 info "Installing prerequisites..."
@@ -58,13 +56,13 @@ sudo pacman -Syu
 cd "$(mktempd)" || exit 1
 
 # Install "yay" from AUR
-if hash yay 2> /dev/null; then
-    success "yay already installed!"
+if hash yay 2>/dev/null; then
+	success "yay already installed!"
 else
-    info "Installing yay"
-    curl -o PKGBUILD "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=yay-bin"
-    makepkg PKGBUILD
-    sudo pacman -U yay*.tar.xz --noconfirm
+	info "Installing yay"
+	curl -o PKGBUILD "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=yay-bin"
+	makepkg PKGBUILD
+	sudo pacman -U yay*.tar.xz --noconfirm
 fi
 
 # Return to latest dir
diff --git a/dependencies/dependencies-macOS b/dependencies/dependencies-macOS
--- a/dependencies/dependencies-macOS
+++ b/dependencies/dependencies-macOS
@@ -2,42 +2,46 @@
 
 # Install command-line tools using Homebrew.
 
-CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-function brew-alloptions () {
-    brew install "$1 $(brew options "$1" | grep -E '^--with-' - | tr '\n' ' ')"
+function brew-alloptions() {
+	brew install "$1 $(brew options "$1" | grep -E '^--with-' - | tr '\n' ' ')"
 }
 
 # Ask for the administrator password upfront.
 sudo -v
 
-info () {
-    printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
+info() {
+	printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
 }
 
-user () {
-    printf "\r  [ \033[0;33m??\033[0m ] %s\n" "$1"
+user() {
+	printf "\r  [ \033[0;33m??\033[0m ] %s\n" "$1"
 }
 
-success () {
-    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
+success() {
+	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
 }
 
-fail () {
-    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
-    echo ''
-    exit
+fail() {
+	printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
+	echo ''
+	exit
 }
 # Keep-alive: update existing `sudo` time stamp until the script has finished.
-while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
+while true; do
+	sudo -n true
+	sleep 60
+	kill -0 "$$" || exit
+done 2>/dev/null &
 
 # Checking if Homebrew is installed
-if ! type -p brew > /dev/null ; then
-    # Install Homebrew
-    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+if ! type -p brew >/dev/null; then
+	# Install Homebrew
+	bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 else
-    # Update homebrew.
-    brew update
+	# Update homebrew.
+	brew update
 fi
 
 cd "$CURRENT_DIR" || exit 1
@@ -49,12 +53,11 @@ info "Installing packages"
 brew bundle
 
 info "Installing python packages"
-pip3 install neovim\
-pynvim \
-jedi \
-mistune \
-psutil \
-setproctitle
+pip3 install neovimpynvim \
+	jedi \
+	mistune \
+	psutil \
+	setproctitle
 
 # Remove outdated versions from the cellar.
 brew cleanup
