Updated path_candidate and added method for editing with fzf search

diff --git a/dependencies/qlInstall b/dependencies/qlInstall
--- a/dependencies/qlInstall
+++ b/dependencies/qlInstall
@@ -33,16 +33,12 @@ brew cask install webpquicklook
 # All Quick Look-plugins that aren't in homebrew
 echo Installing/Downloading Quick Look-plugins that are not from Homebrew
 echo THEY MIGHT BE OUTDATED
-curl -o "$HOME/Library/QuickLook/QLStephen.qlgenerator" https://raw.github.com/Croxed/osx-init/master/extras/QLStephen.qlgenerator
+# Failsafe if cd doesn't work
+cd "$HOME/Library/QuickLook/" || exit 1
 
-# Downloading the plugins
-curl -o "$HOME/Library/QuickLook/1.zip" http://repo.whine.fr/qlmoviepreview.qlgenerator-10.9.zip
-curl -o "$HOME/Library/QuickLook/2.zip" http://ipaql.com/site/assets/files/1006/ipaql_1-3-0.zip
-curl -o "$HOME/Library/QuickLook/3.zip" http://blog.timac.org/post-images/StringsFileQuickLook/StringsFile.qlgenerator.zip
+curl -fSsL https://github.com/whomwah/qlstephen/releases/download/1.4.4/QLStephen.qlgenerator.1.4.4.zip -o QLStephen.zip
 
 # Moving into QuickLook-folder to extract the .zip's
-# Failsafe if cd doesn't work
-cd "$HOME/Library/QuickLook" || exit
 for filename in ./*.zip; do
 	unzip -q "$filename"
 done
